User Story 1: Setup Gallery with Items
Long-HaHoang/capstone-project pull request #4
Opened 2023-01-20 13:51 UTC by Long-HaHoang

- Adding a Title Header on top
- Mapping through a JSON to get items
- Setting up a gallery view of items
- Added temporary styling to the site

2023-01-20 14:34 UTC, JoergWolff commented
LGTM

2023-01-20 15:09 UTC, d-opri approved these changes
looks good to me :)

2023-01-20 15:20 UTC, F-Kirchhoff requested changes
Very nice Long, besides minor CSS suggesetions you are ready to go!

2023-01-20 15:20 UTC, F-Kirchhoff commented on pages/index.js
> +        {/* TODO: refactor component in the next user story */}
please leave no TODOs in your PR

2023-01-20 15:20 UTC, F-Kirchhoff commented on pages/index.js
> +  width: 375px;
You should not set the width of your app container to a fixed size, it should stay responsive. You can preview the app in the mobile view in your browser.

2023-01-20 15:20 UTC, F-Kirchhoff commented on pages/index.js
> +  flex-wrap: wrap;
you can delete this property

2023-01-20 15:20 UTC, F-Kirchhoff commented on pages/index.js
> +  height: 192px;
You should not use fixed width and height values, this is not responsive

2023-01-21 09:34 UTC, d-opri approved these changes

2023-01-21 09:34 UTC, d-opri commented on pages/index.js
> +    <AppContainer>
im sure you will come back to this later on (i think you had a todo comment) but just case: you may want to create a Layout component, for a better overview. if you need a different layout for other pages you can also create a NestedLayout component and add a property getLayout to your page. [This is the Next.js page im referencing](https://nextjs.org/docs/basic-features/layouts)

2023-01-21 11:15 UTC, merged